config/routes.rb
Campusfoodie::Application.routes.draw do

  resources :uservotes

  match "/users/login" => "users#login"
  match "/users/signIn" => "users#signIn"
  match "/campus_foods/today" => "campus_foods#today"
  match "/campus_foods/future" => "campus_foods#future"
  match "/campus_foods/search" => "campus_foods#search"
  resources :users

  resources :locations

  resources :campus_foods

  root :to => 'users#login'

end

app/models/uservote.rb
class Uservote < ActiveRecord::Base
end

app/controllers/uservotes_controller.rb
class UservotesController < ApplicationController
  # GET /uservotes
  # GET /uservotes.json
  def index
    @uservotes = Uservote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uservotes }
    end
  end

  # GET /uservotes/1
  # GET /uservotes/1.json
  def show
    @uservote = Uservote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uservote }
    end
  end

  # GET /uservotes/new
  # GET /uservotes/new.json
  def new
    @uservote = Uservote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uservote }
    end
  end

  # GET /uservotes/1/edit
  def edit
    @uservote = Uservote.find(params[:id])
  end

  # POST /uservotes
  # POST /uservotes.json
  def create
    @uservote = Uservote.new(params[:uservote])
    fuid =      params[:uservote][:fuid]
    eventid =    params[:uservote][:eventid]
    @entry = Uservote.find(:all,:conditions=> ["fuid like ? and eventid like ? ", "#{fuid}","#{eventid}"])
    Rails.logger.info("fuid is #{fuid}, event id is : #{eventid}, entry is #{@entry}")
    if !@entry.empty?
           render :json => { :status => :error, :message => "Duplicate entry" }.to_json, :status => 400
    else
      respond_to do |format|
      if @uservote.save
        format.html { redirect_to @uservote, notice: 'Uservote was successfully created.' }
        format.json { render json: @entry, status: :created, location: @uservote }
      else
        format.html { render action: "new" }
        format.json { render json: @uservote.errors, status: :unprocessable_entity }
      end
      end

    end

  end

  # PUT /uservotes/1
  # PUT /uservotes/1.json
  def update
    @uservote = Uservote.find(params[:id])

    respond_to do |format|
      if @uservote.update_attributes(params[:uservote])
        format.html { redirect_to @uservote, notice: 'Uservote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @uservote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uservotes/1
  # DELETE /uservotes/1.json
  def destroy
    @uservote = Uservote.find(params[:id])
    @uservote.destroy

    respond_to do |format|
      format.html { redirect_to uservotes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/uservotes_helper.rb
module UservotesHelper
end

app/views/uservotes/_form.html.erb
<%= form_for(@uservote) do |f| %>
  <% if @uservote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uservote.errors.count, "error") %> prohibited this uservote from being saved:</h2>

      <ul>
      <% @uservote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fuid %><br />
    <%= f.text_field :fuid %>
  </div>
  <div class="field">
    <%= f.label :eventid %><br />
    <%= f.number_field :eventid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uservotes/edit.html.erb
<h1>Editing uservote</h1>

<%= render 'form' %>

<%= link_to 'Show', @uservote %> |
<%= link_to 'Back', uservotes_path %>

app/views/uservotes/index.html.erb
<h1>Listing uservotes</h1>

<table>
  <tr>
    <th>Fuid</th>
    <th>Eventid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uservotes.each do |uservote| %>
  <tr>
    <td><%= uservote.fuid %></td>
    <td><%= uservote.eventid %></td>
    <td><%= link_to 'Show', uservote %></td>
    <td><%= link_to 'Edit', edit_uservote_path(uservote) %></td>
    <td><%= link_to 'Destroy', uservote, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uservote', new_uservote_path %>

app/views/uservotes/new.html.erb
<h1>New uservote</h1>

<%= render 'form' %>

<%= link_to 'Back', uservotes_path %>

app/views/uservotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fuid:</b>
  <%= @uservote.fuid %>
</p>

<p>
  <b>Eventid:</b>
  <%= @uservote.eventid %>
</p>


<%= link_to 'Edit', edit_uservote_path(@uservote) %> |
<%= link_to 'Back', uservotes_path %>