config/routes.rb
Campusfoodie::Application.routes.draw do

  resources :uservotes

  match "/users/login" => "users#login"
  match "/users/signIn" => "users#signIn"
  match "/campus_foods/today" => "campus_foods#today"
  match "/campus_foods/future" => "campus_foods#future"
  match "/campus_foods/search" => "campus_foods#search"
  resources :users

  resources :locations

  resources :campus_foods

  root :to => 'users#login'

end

app/models/campus_food.rb
class CampusFood < ActiveRecord::Base
end

app/controllers/campus_foods_controller.rb
class CampusFoodsController < ApplicationController
  # GET /campus_foods
  # GET /campus_foods.json
  def index
    @campus_foods = CampusFood.all
    #for each in @campus_foods
     # each.start.to_time
      #each.end.to_time
    #end
    #@campus_foods.sort_by(&:start)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campus_foods }
    end
  end

   def today
    #@campus_foods = CampusFood.find_all_by_date(Date.today)
     @campus_foods = CampusFood.all(:conditions => ["date = ?",Date.today] ,:order => 'date,start')
    #for each in @campus_foods
     # each.start.to_time
      #each.end.to_time
    #end
    #@campus_foods.sort_by(&:start)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campus_foods }
    end
   end

  def future
    @campus_foods = CampusFood.all(:conditions => ["date > ?",Date.today],:order => 'date,start')
    #for each in @campus_foods
     # each.start.to_time
      #each.end.to_time
    #end
    #@campus_foods.sort_by(&:start)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campus_foods }
    end
  end

  def search
    @food = params[:food]
    @results = CampusFood.find(:all, :conditions => ["food like ?", "%#{@food}%"])
    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @results }
    end
  end
  # GET /campus_foods/1
  # GET /campus_foods/1.json
  def show
    @campus_food = CampusFood.find(params[:id])
	@loc = params[:loc]
	
	@locations = Location.all(:conditions =>[ "loc like ? ", "%#{params[:loc]}%"])
	if !@locations.empty?
   @lat = @locations[0].lat
   @lng = @locations[0].lng
  end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /campus_foods/new
  # GET /campus_foods/new.json
  def new
    @campus_food = CampusFood.new
	@locations = Location.all
	@temp = []
	for each in @locations
		@temp.push(each.loc.to_s)
	end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campus_food }
    end
  end

  # GET /campus_foods/1/edit
  def edit
    @campus_food = CampusFood.find(params[:id])
    @temp = []
    @locations = Location.all
    if !@locations.nil?
      for each in @locations
        @temp.push(each.loc.to_s)
      end
    end

  end

  # POST /campus_foods
  # POST /campus_foods.json
  def create
    @campus_food = CampusFood.new(params[:campus_food])
	#@campus_food.location = params[:tags]
    respond_to do |format|
      if @campus_food.save
        format.html { redirect_to campus_foods_path, notice: 'Campus food was successfully created.' }
        format.json { render json: @campus_food, status: :created, location: @campus_food }
      else
        format.html { render action: "new" }
        format.json { render json: @campus_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campus_foods/1
  # PUT /campus_foods/1.json
  def update
    @campus_food = CampusFood.find(params[:id])
	@campus_food.location = params[:tags]
    respond_to do |format|
      if @campus_food.update_attributes(params[:campus_food])
        format.html { redirect_to campus_foods_path, notice: 'Campus food was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @campus_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus_foods/1
  # DELETE /campus_foods/1.json
  def destroy
    @campus_food = CampusFood.find(params[:id])
    @campus_food.destroy

    respond_to do |format|
      format.html { redirect_to campus_foods_url }
      format.json { head :ok }
    end
  end
end

app/helpers/campus_foods_helper.rb
module CampusFoodsHelper
end

app/views/campus_foods/_form.html.erb
<%= form_for(@campus_food) do |f| %>
  <% if @campus_food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campus_food.errors.count, "error") %> prohibited this campus_food from being saved:</h2>

      <ul>
      <% @campus_food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<head>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src = " https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src = " https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script>
	$(function() {
		var availableTags = ["<%= @temp[0] %>","<%= @temp[1] %>","<%= @temp[2] %>","<%= @temp[3] %>","<%= @temp[4] %>","<%= @temp[5] %>","<%= @temp[6] %>"];
		$( "#campus_food_location" ).autocomplete({
			source: availableTags
		});
	});
	</script>

</head>
	
<div class="demo">



</div><!-- End demo -->

<div style="border:2px solid #CFECEC;border-radius: 10px;box-shadow: rgba(0,0,0,0.4) 2px 2px 0 2px;margin-left:3%; width:60%">


  <div class="field">
    <%= f.label :title, 'Event Title*' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :food, 'Free food*' %><br />
    <%= f.text_field :food %>
  </div>
  <div class="ui-widget">
       <label for="campus_food_location">Locations: </label> <br />
       <input type="text" id="campus_food_location" name="campus_food[location]">
       <%= link_to 'Or Add New Location', :controller => 'locations', :action=> 'new' %>
  </div>
  <br />
  <div class="field">
    <%= f.label :date, 'Date*' %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start, 'Starts at*' %><br />
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :end, 'Ends at*' %><br />
    <%= f.text_field :end %>
  </div>
  <div class="field", 'Event type'>
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field" 'Description'>
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :cols =>30, :rows =>5%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/campus_foods/edit.html.erb
<h2 style="color:#3300CC;margin-left:3%;">Edit campus food event</h2><br/>

<%= render 'form' %>
<div style="margin-left:3%">
<br/>
<%= link_to 'Show', @campus_food %> |
<%= link_to 'Back', campus_foods_path %>
</div>

app/views/campus_foods/future.html.erb
<br/><h2 style="color:#3300CC;">Soon to be held campus free food events!!</h2><br/>

<table>
  <tr>
    <th style="width:120px">Event Title</th>
    <th style="width:120px">Free Food</th>
    <th style="width:120px">Location</th>
    <th style="width:120px">Date</th>
    <th style="width:90px">Starts at</th>
    <th style="width:90px">Ends at</th>
    <th style="width:150px">Description</th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
  </tr>

<% @campus_foods.each do |campus_food| %>
  <tr <%- if campus_food.id % 2 !=0%> id="odd" <%-end-%>>
    <td style="padding:none;width:120px; text-align:center;"><%= campus_food.title %></td>
    <td style="width:120px;text-align:center;"><%= campus_food.food %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.location %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.date %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.start %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.end %></td>
    <td style="width:150px; text-align:center;"><%= campus_food.desc %></td>
    <td style="width:50px"><%= link_to 'Show', :controller => 'campus_foods', :action =>'show', :id => campus_food.id, :loc => campus_food.location %></td>
    <td style="width:50px"><%= link_to 'Edit', edit_campus_food_path(campus_food) %></td>
    <% if session[:admin_user] == true %> <td style="width:50px"><%= link_to 'Destroy', campus_food, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a new campus food event!', new_campus_food_path %>

app/views/campus_foods/index.html.erb
<br/><h2 style="color:#3300CC;">All Campus free foods!!</h2><br/>

<h1> Search for Campus events by food</h1>
<form action="/campus_foods/search" method="get" id="search_form">
    <input id="food" class="searchBox" type="text" name="food"/>
    <input type="submit"  class="searchButton"  value="search"/>

  </form>

<table>
  <tr>
    <th style="width:120px">Event Title</th>
    <th style="width:120px">Free Food</th>
    <th style="width:120px">Location</th>
    <th style="width:120px">Date</th>
    <th style="width:90px">Starts at</th>
    <th style="width:90px">Ends at</th>
    <th style="width:150px">Description</th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
  </tr>

<% @campus_foods.sort_by(&:start).each do |campus_food| %>
  <tr <%- if campus_food.id % 2 !=0%> id="odd" <%-end-%>>
    <td style="padding:none;width:120px; text-align:center;"><%= campus_food.title %></td>
    <td style="width:120px;text-align:center;"><%= campus_food.food %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.location %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.date %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.start %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.end %></td>
    <td style="width:150px; text-align:center;"><%= campus_food.desc %></td>
    <td style="width:50px"><%= link_to 'Show', :controller => 'campus_foods', :action =>'show', :id => campus_food.id, :loc => campus_food.location %></td>
    <td style="width:50px"><%= link_to 'Edit', edit_campus_food_path(campus_food) %></td>
    <% if session[:admin_user] == true %> <td style="width:50px"><%= link_to 'Destroy', campus_food, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a new campus food event!', new_campus_food_path %>

app/views/campus_foods/new.html.erb
<h2 style="color:#3300CC; margin-left:3%;">Create a new Campus food event!</h2>

<%= render 'form' %>
<br/>
<p style="margin-left:3%;" ><%= link_to 'Back', campus_foods_path %></p>

app/views/campus_foods/search.html.erb
<br/><h2 style="color:#3300CC;">Search results</h2><br/>

<table>
  <tr>
    <th style="width:120px">Event Title</th>
    <th style="width:120px">Free Food</th>
    <th style="width:120px">Location</th>
    <th style="width:120px">Date</th>
    <th style="width:90px">Starts at</th>
    <th style="width:90px">Ends at</th>
    <th style="width:150px">Description</th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
  </tr>

<% @results.sort_by(&:start).each do |campus_food| %>
  <tr <%- if campus_food.id % 2 !=0%> id="odd" <%-end-%>>
    <td style="padding:none;width:120px; text-align:center;"><%= campus_food.title %></td>
    <td style="width:120px;text-align:center;"><%= campus_food.food %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.location %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.date %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.start %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.end %></td>
    <td style="width:150px; text-align:center;"><%= campus_food.desc %></td>
    <td style="width:50px"><%= link_to 'Show', :controller => 'campus_foods', :action =>'show', :id => campus_food.id, :loc => campus_food.location %></td>
    <td style="width:50px"><%= link_to 'Edit', edit_campus_food_path(campus_food) %></td>
    <% if session[:admin_user] == true %> <td style="width:50px"><%= link_to 'Destroy', campus_food, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a new campus food event!', new_campus_food_path %>

app/views/campus_foods/show.html.erb
<div style="border:2px solid #CFECEC;border-radius: 10px;box-shadow: rgba(0,0,0,0.4) 2px 2px 0 2px;margin-left:3%; width:60%;text-indent:20px;">
<p id="notice"><%= notice %></p>

<p>
  <b>Event Title:</b>
  <%= @campus_food.title %>
</p>

<p>
  <b>Free Food:</b>
  <%= @campus_food.food %>
</p>

<p>
  <b>Location:</b>
  <%= @campus_food.location %>
</p>

<p>
  <b>Date:</b>
  <%= @campus_food.date %>
</p>

<p>
  <b>Starts at:</b>
  <%= @campus_food.start %>
</p>

<p>
  <b>Ends at:</b>
  <%= @campus_food.end %>
</p>

<p>
  <b>Description:</b>
  <%= @campus_food.desc %>
</p>

<script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
		var map;
		var i=0;
		var pic;
		var marker;
        <%- if !@lat.nil? and !@lng.nil? -%>
		    var lat = <%=@locations[0].lat%>;
		    var lng = <%=@locations[0].lng%>;
        <%- end -%>
		function initialize() {
			var myOptions = {
			  zoom: 10,
			  center: new google.maps.LatLng(lat, lng),
			  mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById('map_canvas'),
				myOptions);
				
		}	  
		google.maps.event.addDomListener(window, 'load', initialize);  

    </script>
	     
			<input type="text" name="title" id="title" value=""
						style="width: 700px; height: 30px; border:none" readonly="readonly" />
		<div class="map" id="map_canvas" style="width: 500px; height: 300px"></div>
</body>



</div>

<div style="margin-left:3%">
<br/>
<%= link_to 'Edit', edit_campus_food_path(@campus_food) %> |
<%= link_to 'Back', campus_foods_path %>
</div>

app/views/campus_foods/today.html.erb
<br/><h2 style="color:#3300CC;">Today's Campus free foods!!</h2><br/>

<table>
  <tr>
    <th style="width:120px">Event Title</th>
    <th style="width:120px">Free Food</th>
    <th style="width:120px">Location</th>
    <th style="width:120px">Date</th>
    <th style="width:90px">Starts at</th>
    <th style="width:90px">Ends at</th>
    <th style="width:150px">Description</th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
    <th style="width:50px"></th>
  </tr>

<% @campus_foods.sort_by(&:start).each do |campus_food| %>
  <tr <%- if campus_food.id % 2 !=0%> id="odd" <%-end-%>>
    <td style="padding:none;width:120px; text-align:center;"><%= campus_food.title %></td>
    <td style="width:120px;text-align:center;"><%= campus_food.food %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.location %></td>
    <td style="width:120px; text-align:center;"><%= campus_food.date %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.start %></td>
    <td style="width:90px; text-align:center;"><%= campus_food.end %></td>
    <td style="width:150px; text-align:center;"><%= campus_food.desc %></td>
    <td style="width:50px"><%= link_to 'Show', :controller => 'campus_foods', :action =>'show', :id => campus_food.id, :loc => campus_food.location %></td>
    <td style="width:50px"><%= link_to 'Edit', edit_campus_food_path(campus_food) %></td>
    <% if session[:admin_user] == true %> <td style="width:50px"><%= link_to 'Destroy', campus_food, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a new campus food event!', new_campus_food_path %>