config/routes.rb
Campusfoodie::Application.routes.draw do

  resources :uservotes

  match "/users/login" => "users#login"
  match "/users/signIn" => "users#signIn"
  match "/campus_foods/today" => "campus_foods#today"
  match "/campus_foods/future" => "campus_foods#future"
  match "/campus_foods/search" => "campus_foods#search"
  resources :users

  resources :locations

  resources :campus_foods

  root :to => 'users#login'

end

app/models/user.rb
require "digest/sha2"
class User < ActiveRecord::Base
	has_many :campus_foods
	
	

     def authenticate(username, password)
      user = User.find_by_uname(username)
      if user
		if user.passwd != password
			user = nil
		end
		user
	 end
     end


    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def login
  
  end
  
  def signIn
    session[:current_user_id] = nil
    session[:admin_user] = nil
    @user = User.find_by_uname(params[:uname])
    if @user == nil || !@user.authenticate(params[:uname], params[:password])
      flash[:alert] = "Unable to log in to the system. Please check your credentials"
      #redirect_to :action => "index"
    elsif @user.authenticate(params[:uname], params[:password])
      session[:current_user_id] = @user.id
      flash[:notice] = "Successfully Logged in"
      if @user.admin?
        session[:admin_user] = true
        flash[:notice] = "Admin logged in"
      end
      redirect_to(:controller => "campus_foods", :action => "index")
      end
  end

  def logout
    session[:current_user_id] = nil
    session[:admin_user]= nil
    flash[:alert] = "Successfully Logged out"
    redirect_to :action => "index"
  end	
	
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %><br />
    <%= f.text_field :uname %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :passwd %><br />
    <%= f.password_field :passwd %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uname</th>
    <th>Name</th>
    <th>Email</th>
    <th>Passwd</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uname %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.passwd %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div style="background-color:#CFECEC; height:100px;"><br/><h1 style="color:#3300CC;">Campus Free Food App</h1></div>

<p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
<div id="login" style="margin-left:35%;width:30%;border: 1px solid #154A6F;border-radius: 10px;box-shadow: rgba(0,0,0,0.4) 2px 2px 0 2px;text-indent:60px; color:#3300CC;" class="login">
  <span>Sign in to Campus Food App</span>
  <form style="margin-left:20px;" action="/users/signIn" method="post">
    <br/>User ID:   <br/>
    <input id="userId" type="text" name="uname" style="width: 140px;"/>
    <br/>
     Password:   <br/>
    <input id="password" type="password" name="password" style="width: 140px;"/>
    <br/>  <br/>
    <input type="submit" id="signIn" value="Sign in"/>  <%= link_to 'New User', new_user_path %>  <span style="font-size: 7pt;">(Sign up here for a new account)</span>
	<br/><br/>
  </form>
</div>

app/views/users/new.html.erb
<h1>Create an account to post about an event!</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uname:</b>
  <%= @user.uname %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>



<b><%= link_to 'Check out the food events!', campus_foods_path %></b> 

app/views/users/signIn.html.erb
<h4 style="color:#007700;">Campus Free Food App</h4>

<p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
<div id="login" class="login">
  <span>Campus Food App</span>
  <form action="/users/signIn" method="post">
    <br/>User ID:   <br/>
    <input id="userId" type="text" name="uname" style="width: 140px;"/>
    <br/>
     Password:   <br/>
    <input id="password" type="password" name="password" style="width: 140px;"/>
    <br/>  <br/>
    <input type="submit" id="signIn" value="Sign in"/>  <%= link_to 'New User', new_user_path %>  <span style="font-size: 7pt;">(Sign up here for a new account)</span>
  </form>
</div>