config/routes.rb
Campusfoodie::Application.routes.draw do

  resources :uservotes

  match "/users/login" => "users#login"
  match "/users/signIn" => "users#signIn"
  match "/campus_foods/today" => "campus_foods#today"
  match "/campus_foods/future" => "campus_foods#future"
  match "/campus_foods/search" => "campus_foods#search"
  resources :users

  resources :locations

  resources :campus_foods

  root :to => 'users#login'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
	s = Geocoder.search(@location.loc.to_s)
	@temp = s[0].address
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new
	@location.loc = params[:location][:loc]
	s = Geocoder.search(params[:location][:loc])
	@location.lat = s[0].latitude
	@location.lng = s[0].longitude

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="border:2px solid #CFECEC;border-radius: 10px;box-shadow: rgba(0,0,0,0.4) 2px 2px 0 2px;margin-left:3%; width:60%;text-indent:20px;">

  <div class="field">
    <%= f.label :loc, 'Location'%><br />
    <%= f.text_field :loc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.loc %></td>
    <td><%= location.lat %></td>
    <td><%= location.lng %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h2 style="color:#3300CC; margin-left:3%;">New location</h2>

<%= render 'form' %>
<br/>
<p style="margin-left:3%"><%= link_to 'Back', locations_path %></p>

app/views/locations/show.html.erb
<body onload="initialize()">
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @location.loc %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.lat %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.lng %>
</p>

<p>
  <b>Address:</b>
  <%= @temp %>
</p>


    <script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
		var map;
		var i=0;
		var pic;
		var marker;
		var lat = <%=@location.lat%>;
		var lng = <%=@location.lng%>;
		function initialize() {
			var myOptions = {
			  zoom: 15,
			  // center: new google.maps.LatLng(, ),
			  center: new google.maps.LatLng(lat, lng),
			  //center: new google.maps.Address('D.H. Hill Library, North Carolina State University, Raleigh, NC 27607, USA'),
			  mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById('map_canvas'),
				myOptions);
				
			markers = new google.maps.Marker({
					position: new google.maps.LatLng(lat, lng),
					map: map,
					title:"sup"
				});

					
		}	  
		google.maps.event.addDomListener(window, 'load', initialize);  

    </script>
	
			<input type="text" name="title" id="title" value=""
						style="width: 1200px; height: 30px; border:none" readonly="readonly" />
		<div class="map" id="map_canvas" style="width: 500px; height: 300px"></div>
</body>







<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>